### ISSUE TITLE
Daily progress rate is overesatimated

### ISSUE THREAD

**Issue by vincentdephily** [osmie/osm-irish-townlands#113]
https://www.townlands.ie/progress/rate/ today shows 8.8%/day for the whole of Ireland, and the individual counties are similarly overestimated. It's been like that for a while (with different figures each day of course).

My uneducated guess is that the code is looking at a true 24h timespan when measuring the increase but only looking at the fraction of the day (midnight to current processing time) when measuring the duration. And then incorrectly multiplies the measured increase to get the increase over a whole day. The other timespans (month, 90days, etc) would also be affected but less visibly.

**Comment by rory** [comment]
Initially, I calculated the percentage at each import, and saved the values. "For this date, the coverage was X square metres". Those values were retained each import. This is why it starts at 26 Feb 2014, because that's when I started recording them (cripes was it that long ago?!)

However, now I fetch and save the datetime that the object was added to OSM. I could use this data to get much more accurate figures, and could go back to the start as well. That is probably a better way to do it than to fix the old calculation.

**Comment by vincentdephily** [comment]
I like the idea of a calculation using "This TD accounts for x% coverage today and was added on YYYY-MM-DD". There is the case of TDs significantly changing size over time, but the error is probably acceptable. Being able to recalculate the historicat coverage at each import has a certain appeal.

Ideally we'd look at old geometries too, but that's unavailable, right ?
